# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: todo.proto for package 'com.example.demo.todostore'

require 'grpc'
require 'todo_pb'

module Com
  module Example
    module Demo
      module Todostore
        module Todostore
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'com.example.demo.todostore.Todostore'

            rpc :ListTodos, ListTodosRequest, ListTodosResponse
            rpc :GetTodo, GetTodoRequest, GetTodoResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
