# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "todostore.GetTodosRequest" do
  end
  add_message "todostore.GetTodosResponse" do
    repeated :todo, :message, 1, "todostore.Todo"
  end
  add_message "todostore.GetTodoRequest" do
    optional :id, :int64, 1
  end
  add_message "todostore.GetTodoResponse" do
    optional :todo, :message, 1, "todostore.Todo"
  end
  add_message "todostore.Todo" do
    optional :id, :int64, 1
    optional :content, :string, 2
  end
end

module Todostore
  GetTodosRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("todostore.GetTodosRequest").msgclass
  GetTodosResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("todostore.GetTodosResponse").msgclass
  GetTodoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("todostore.GetTodoRequest").msgclass
  GetTodoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("todostore.GetTodoResponse").msgclass
  Todo = Google::Protobuf::DescriptorPool.generated_pool.lookup("todostore.Todo").msgclass
end
